### ISSUE TITLE
Don't reorder "pinned" tabs

### ISSUE THREAD

**Issue by svetlyak40wt** [bmamlin/tabstack.safariextension#1]
Usually, I manually order pinned tabs. This makes possible quickly switch between them using Cmd+1, Cmd+2, etc. keys.

But this extension reorders them after given delay as it does with usual tabs.

Is it possible to change this behaviour and don't touch pinned tabs?

Update: I didn't find a way how to distinguish pinned and not pinned tabs in Safari's API :(

**Comment by lebigot** [comment]
The reordering seems to be working well when reading non-pinned tabs, but behaves in a cumbersome way when closing the first non-pinned tab (the selection moves to the first pinned tab, which I don't want to read just right now :).

**Comment by svetlyak40wt** [comment]
Closing this old issue. Thanks to https://12forks.com MVP for pointing to it.
